services:
  financialsummary.api:
    image: financialsummary.api
    container_name: FinancialSummaryApp
    build:
      context: .
      dockerfile: Source/FinancialSummary.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - financialsummary.database
  financialsummary.database:
    image: postgres:latest
    container_name: FinancialSummaryDatabase
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=financialsummary
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  financialsummary.web:
    image: financialsummary.web
    container_name: FinancialSummaryWeb
    build:
      context: ./Frontend/FinancialSummaryWeb 
      dockerfile: ./dockerfile
    ports:
      - 3000:3000
    depends_on:
      - financialsummary.api